// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPSIDS
{
        public const string achievement_rescued_150_jelly_troopers = "CgkI7La6roAbEAIQAg"; // <GPGSID>
        public const string achievement_rescued_all_jelly_troopers = "CgkI7La6roAbEAIQAQ"; // <GPGSID>
        public const string achievement_newbie_rescued_25_troopers = "CgkI7La6roAbEAIQCQ"; // <GPGSID>
        public const string achievement_rescued_200_jelly_troopers = "CgkI7La6roAbEAIQAw"; // <GPGSID>
        public const string leaderboard_jelly_troopers_less_deaths_leaderboard = "CgkI7La6roAbEAIQCA"; // <GPGSID>
        public const string leaderboard_jelly_troopers_main_leaderboard = "CgkI7La6roAbEAIQBg"; // <GPGSID>
        public const string leaderboard_jelly_troopers_best_time_leaderboard = "CgkI7La6roAbEAIQBw"; // <GPGSID>
        public const string achievement_rookie_rescued_50_troopers = "CgkI7La6roAbEAIQBQ"; // <GPGSID>
        public const string achievement_rescued_110_jelly_troopers = "CgkI7La6roAbEAIQBA"; // <GPGSID>
        public const string leaderboard_super_jelly_troopers_more_saved_soldiers = "CgkI7La6roAbEAIQCg"; // <GPGSID>

}

